Remove stop service command

diff --git a/.github/workflows/deploy_workflow-tf.yml b/.github/workflows/deploy_workflow-tf.yml
--- a/.github/workflows/deploy_workflow-tf.yml
+++ b/.github/workflows/deploy_workflow-tf.yml
@@ -27,44 +27,45 @@ jobs:
           role-to-assume: arn:aws:iam::${{ secrets.account_id }}:role/midendev-GithubActionsRole
           role-session-name: GithubActionsSession
 
-      - name: Stop services
-        id: stop_services
-        run: |
-          COMMAND_ID=$(aws ssm send-command \
-            --instance-ids ${{ secrets.instance_id }} \
-            --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":["sudo systemctl stop miden-node", "sudo systemctl stop miden-faucet"]}' \
-            --output text \
-            --query "Command.CommandId")
-          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
+      # - name: Stop services
+      #   id: stop_services
+      #   run: |
+      #     COMMAND_ID=$(aws ssm send-command \
+      #       --instance-ids ${{ secrets.instance_id }} \
+      #       --document-name "AWS-RunShellScript" \
+      #       --parameters '{"commands":["sudo systemctl stop miden-node", "sudo systemctl stop miden-faucet"]}' \
+      #       --output text \
+      #       --query "Command.CommandId")
+      #     echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
 
-      - name: Check stop services command status and retrieve output
-        run: |
-          while true; do
-            STATUS=$(aws ssm list-command-invocations \
-                --command-id ${{ steps.stop_services.outputs.command_id }} \
-                --details \
-                --query "CommandInvocations[0].Status" \
-                --output text)
-            echo "Command Status: $STATUS"
+
+      # - name: Check stop services command status and retrieve output
+      #   run: |
+      #     while true; do
+      #       STATUS=$(aws ssm list-command-invocations \
+      #           --command-id ${{ steps.stop_services.outputs.command_id }} \
+      #           --details \
+      #           --query "CommandInvocations[0].Status" \
+      #           --output text)
+      #       echo "Command Status: $STATUS"
             
-            OUTPUT=$(aws ssm list-command-invocations \
-                --command-id ${{ steps.stop_services.outputs.command_id }} \
-                --details \
-                --query "CommandInvocations[0].CommandPlugins[0].Output" \
-                --output text)
-            echo "Command Output: $OUTPUT"
+      #       OUTPUT=$(aws ssm list-command-invocations \
+      #           --command-id ${{ steps.stop_services.outputs.command_id }} \
+      #           --details \
+      #           --query "CommandInvocations[0].CommandPlugins[0].Output" \
+      #           --output text)
+      #       echo "Command Output: $OUTPUT"
             
-            if [ "$STATUS" == "Success" ]; then
-              echo "Command completed successfully."
-              break
-            elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
-              echo "Command failed with status: $STATUS"
-              exit 1
-            else
-              sleep 10  # Wait for 30 seconds before checking again
-            fi
-          done
+      #       if [ "$STATUS" == "Success" ]; then
+      #         echo "Command completed successfully."
+      #         break
+      #       elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
+      #         echo "Command failed with status: $STATUS"
+      #         exit 1
+      #       else
+      #         sleep 10  # Wait for 30 seconds before checking again
+      #       fi
+      #     done
       
       # - name: Recreate app folders
       #   id: install_prereq
@@ -208,9 +209,9 @@ jobs:
                 "sudo systemctl daemon-reload",
                 "sudo systemctl enable miden-node",
                 "sudo systemctl enable miden-faucet",
-                "sudo systemctl start miden-node",
+                "sudo systemctl restart miden-node",
                 "sleep 5",
-                "sudo systemctl start miden-faucet"
+                "sudo systemctl restart miden-faucet"
               ]}' \
             --output text \
             --query "Command.CommandId")
